# Generated by Django 5.1.1 on 2024-09-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('img', models.URLField()),
                ('followers', models.IntegerField()),
                ('followings', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Insta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('img', models.URLField()),
                ('follower', models.BooleanField(default=False)),
                ('following', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('profile', 'user')},
            },
        ),
    ]
